[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "tests/foundry"
verbosity = 5
evm_version = "paris"

[fuzz]
runs = 1_000

remappings = ["forge-std/=lib/forge-std/src/", "@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options